plugins {
    id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}


repositories {
    // YetAnotherConfigLib.
    maven {
        name 'Xander Maven'
        url 'https://maven.isxander.dev/releases'
    }

    // Twitch4J.
    maven { url "https://maven.awakenedredstone.com"}

    // ModMenu.
    maven {
        name 'Terraformers'
        url 'https://maven.terraformersmc.com/'
    }

    // DevAuth.
    maven { url = "https://pkgs.dev.azure.com/djtheredstoner/DevAuth/_packaging/public/maven/v1" }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API.
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    // Adventure.
    modImplementation include("net.kyori:adventure-platform-fabric:${project.adventure_version}")
    // YetAnotherConfigLib.
    modImplementation "dev.isxander:yet-another-config-lib:${project.yacl_version}"

    // ModMenu.
    modImplementation("com.terraformersmc:modmenu:${project.modmenu_version}")

    // DevAuth.
    modRuntimeOnly("me.djtheredstoner:DevAuth-fabric:${project.devauth_version}")

    // Twitch4J.
    include modApi("com.github.twitch4j:twitch4j:${project.library_version}") {
        exclude group: "org.slf4j", module: "slf4j-api"
    }
    include "com.github.twitch4j:twitch4j-auth:${project.library_version}"
    include "com.github.twitch4j:twitch4j-chat:${project.library_version}"
    include "com.github.twitch4j:twitch4j-client-websocket:${project.library_version}"
    include "com.github.twitch4j:twitch4j-common:${project.library_version}"
    include "com.github.twitch4j:twitch4j-eventsub-common:${project.library_version}"
    include "com.github.twitch4j:twitch4j-eventsub-websocket:${project.library_version}"
    include "com.github.twitch4j:twitch4j-extensions:${project.library_version}"
    include "com.github.twitch4j:twitch4j-graphql:${project.library_version}"
    include "com.github.twitch4j:twitch4j-helix:${project.library_version}"
    include "com.github.twitch4j:twitch4j-kraken:${project.library_version}"
    include "com.github.twitch4j:twitch4j-messaginginterface:${project.library_version}"
    include "com.github.twitch4j:twitch4j-pubsub:${project.library_version}"
    include "com.github.twitch4j:twitch4j-util:${project.library_version}"

    var apollo = "2.5.14"
    var events4j = "0.12.2"
    var jackson = "2.19.0"
    var openfeign = "13.6"
    var xanthic = "0.7.1"

    include "com.apollographql.apollo:apollo-api-jvm:$apollo"
    include "com.apollographql.apollo:apollo-http-cache-api:$apollo"
    include "com.apollographql.apollo:apollo-normalized-cache-api-jvm:$apollo"
    include "com.apollographql.apollo:apollo-normalized-cache-jvm:$apollo"
    include "com.apollographql.apollo:apollo-runtime:$apollo"
    include "com.benasher44:uuid-jvm:0.2.0"
    include "com.bucket4j:bucket4j_jdk8-core:8.10.1"
    include "com.fasterxml.jackson.core:jackson-annotations:$jackson"
    include "com.fasterxml.jackson.core:jackson-core:$jackson"
    include "com.fasterxml.jackson.core:jackson-databind:$jackson"
    include "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:$jackson"
    include "com.github.ben-manes.caffeine:caffeine:2.9.3"
    include "com.github.philippheuer.credentialmanager:credentialmanager:0.3.1"
    include "com.github.philippheuer.events4j:events4j-api:$events4j"
    include "com.github.philippheuer.events4j:events4j-core:$events4j"
    include "com.github.philippheuer.events4j:events4j-handler-simple:$events4j"
    include "com.github.tony19:named-regexp:1.0.0"
    include "com.google.errorprone:error_prone_annotations:2.10.0"
    include "com.neovisionaries:nv-websocket-client:2.14"
    include "com.netflix.archaius:archaius-core:0.4.1"
    include "com.netflix.hystrix:hystrix-core:1.5.18"
    include "com.nytimes.android:cache:2.0.2"
    include "com.squareup.okhttp3:okhttp:4.12.0"
    include "com.squareup.okio:okio-jvm:3.6.0"
    include "commons-configuration:commons-configuration:1.10"
    include "commons-lang:commons-lang:2.6"
    include "io.github.openfeign:feign-core:$openfeign"
    include "io.github.openfeign:feign-hystrix:$openfeign"
    include "io.github.openfeign:feign-jackson:$openfeign"
    include "io.github.openfeign:feign-okhttp:$openfeign"
    include "io.github.openfeign:feign-slf4j:$openfeign"
    include "io.github.xanthic.cache:cache-api:$xanthic"
    include "io.github.xanthic.cache:cache-core:$xanthic"
    include "io.github.xanthic.cache:cache-provider-caffeine:$xanthic"
    include "io.reactivex:rxjava:1.2.0"
    include "net.fabricmc:fabric-language-kotlin:1.10.19+kotlin.1.9.23"
    include "org.hdrhistogram:HdrHistogram:2.1.9"
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "loader_version", project.loader_version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
                "minecraft_version": project.minecraft_version,
                "loader_version": project.loader_version
    }
}

def targetJavaVersion = 21
tasks.withType(JavaCompile).configureEach {
    // ensure that the encoding is set to UTF-8, no matter what the system default is
    // this fixes some edge cases with special characters not displaying correctly
    // see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
    // If Javadoc is generated, this must be specified in that task too.
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()
}

jar {
    inputs.property "archivesName", project.base.archivesName

    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}" }
    }
}

// configure the maven publication
publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
    }
}
